### ISSUE TITLE
Support rendering collection of values

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/kiota-serialization-form-dotnet#15]
We can add support by adding a key-value pair for each item in the collection.  As per the HTML specification, the data model is a list of name-value tuples https://url.spec.whatwg.org/#urlencoded-serializing
There is no requirement for the name to be unique.  This allows us to represent arrays by repeating the key name for each array value.

https://github.com/microsoft/kiota-serialization-form-dotnet/blob/afda27e91ad299da344bb609b520f95ae6c23650/src/FormSerializationWriter.cs#L58

**Comment by baywet** [comment]
@andrueastman would you mind tackling this one please? It should be a fairly easy implementation
Also I think @darrelmiller meant this method since we don't serialize nested object values.

https://github.com/microsoft/kiota-serialization-form-dotnet/blob/afda27e91ad299da344bb609b520f95ae6c23650/src/FormSerializationWriter.cs#L60

**Comment by baywet** [comment]
(as well as the getCollectionOfPrimitiveValues in the parseNode)

**Comment by andrueastman** [comment]
> @andrueastman would you mind tackling this one please? It should be a fairly easy implementation Also I think @darrelmiller meant this method since we don't serialize nested object values.
> 
> https://github.com/microsoft/kiota-serialization-form-dotnet/blob/afda27e91ad299da344bb609b520f95ae6c23650/src/FormSerializationWriter.cs#L60

Acknowledging this @baywet
